Fix Traefik deploy scripts

diff --git a/2-Traefik/external/deploy b/2-Traefik/external/deploy
--- a/2-Traefik/external/deploy
+++ b/2-Traefik/external/deploy
@@ -8,17 +8,15 @@ fi
 # however some are hardcoded to 'monitoring'. Only use if you have reviewed all manifests.
 
 if [ -z "${NAMESPACE}" ]; then
-    NAMESPACE=traefik
+    NAMESPACE=kube-system
 fi
-
-kubectl create namespace "$NAMESPACE"
 
 kctl() {
     kubectl --namespace "$NAMESPACE" "$@"
 }
 
 if ! [ -x "$(command -v helm)" ]; then
-  echo 'Error: helm is not installed.' >&2
+  echo 'Error: helm is not installed. It is required to deploy the Consul cluster.' >&2
   exit 1
 fi
 
